export { default as cartIcon } from '../assets/images/cart-icon.svg'
export { default as logoIcon } from '../assets/images/logo.svg'
export { default as logoutIcon } from '../assets/images/logout.svg'
export { default as menuIcon } from '../assets/images/menu-icon.svg'
export { default as nonameIcon } from '../assets/images/noname.svg'
export { default as searchIcon } from '../assets/images/search.svg'
export { default as starIcon } from '../assets/images/star.svg'
export { default as userIcon } from '../assets/images/userIcon.svg'
export { default as userPhoto } from '../assets/images/userPhoto.svg'
export { default as addCartIcon } from '../assets/images/addCart.svg'
export { default as closeSearch } from '../assets/images/closeSearch.svg'

